In [1]:
import pandas as pd
import numpy as np

In [10]:
df = pd.read_csv("customer.csv")
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

1. Gender has (M,F) nomial categorical data - One Hot Encoder
2. review(G,P,Avg) ordinal categorical data - Ordinal Encoding
3. education (School,UG,PG) ordinal categorical data - Ordinal Encoding
4. purchased (Y/N) nomial categorical data - Label Encoding

As of now we will ignore age and Gender column

In [11]:
df = df.iloc [:,2:]
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:-1], df.iloc[:,-1], test_size=0.2)

In [14]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])
oe.fit(X_train)
X_train = oe.transform(X_train)
X_test = oe.transform(X_test)

In [15]:
X_train

array([[1., 2.],
       [2., 0.],
       [2., 1.],
       [0., 2.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 2.],
       [1., 2.],
       [0., 0.],
       [0., 2.],
       [0., 0.],
       [2., 2.],
       [1., 0.],
       [1., 1.],
       [0., 1.],
       [0., 1.],
       [1., 1.],
       [0., 0.],
       [2., 0.],
       [2., 2.],
       [2., 1.],
       [2., 2.],
       [0., 2.],
       [0., 2.],
       [0., 2.],
       [2., 1.],
       [2., 0.],
       [0., 1.],
       [2., 1.],
       [2., 0.],
       [1., 1.],
       [0., 2.],
       [1., 2.],
       [2., 1.],
       [2., 0.],
       [2., 0.],
       [0., 1.],
       [1., 1.],
       [0., 0.]])

#Label Encoding

In [20]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(y_train)
y_train = le.transform(y_train)
y_test = le.transform(y_test)

y_train

array([1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0])

#One Hot Encoder

In [22]:
df = pd.read_csv("cars.csv")
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [24]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [25]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,0:4], df.iloc[:,-1], test_size=0.2)

In [28]:
ohe = OneHotEncoder()
X_train_new = ohe.fit_transform(X_train[['fuel','owner']]).toarray()
X_test_new = ohe.transform(X_test[['fuel','owner']]).toarray()